<!-- initialise miromodal.js -->

```{ojs}
//| include: false
micro = require("micromodal@0.4.10")
micro.init({
  awaitOpenAnimation: true,
  awaitCloseAnimation: true
});
```

::::::: {#modal-useremix .modal .micromodal-slide aria-hidden="true"}
:::::: {.modal__overlay tabindex="-1" data-micromodal-close="true"}
::::: {.modal__container role="dialog" aria-modal="true" aria-labelledby="modal-useremix-title"}

<button class="modal__close" aria-label="Close modal" data-micromodal-close></button>

:::: {#modal-useremix-content}
## Use + Remix

These charts, as well as the analyses that underpin them, are available under a [**Creative Commons Attribution 4.0 licence**](https://creativecommons.org/licenses/by/4.0).

Please acknowledge [360info](https://360info.org) and our data sources when you use these charts and data.

#### Embed this chart in your article

Copy and paste the following code:

::: {.embedcode}
```
<iframe
src="https://360info-studentflows.pages.dev/
embed-netflow-scatter" title="Chart with Human
Development Index increasing to the right and Net
Student Ratio increasing upward. Countries situated
above the line, in blue, are receiving more
students from other countries than they send out."
width="550" height="560" scrolling="no"
style="border:none;"></iframe>
```
:::

This content is subject to [360info's Terms of Use](https://newshub.360info.org/page/terms).

#### Get the data and code

Visit the [GitHub repository](https://github.com/360-info/report-template/tree/main/data) to:

* [**Download the data**](https://github.com/360-info/report-template/tree/main/data)
* [**Recreate or remix the chart**](https://github.com/360-info/report-template)
::::

:::::
::::::
:::::::

<!-- notes dialog -->

::::::: {#modal-about .modal .micromodal-slide aria-hidden="true"}
:::::: {.modal__overlay tabindex="-1" data-micromodal-close="true"}
::::: {.modal__container role="dialog" aria-modal="true" aria-labelledby="modal-about-title"}

<button class="modal__close" aria-label="Close modal" data-micromodal-close></button>

<header>
## What do these numbers mean? {#modal-about-title}
</header>

:::: {#modal-about-content}

**Trend Indicator Value** (TIV) is a kind of price that SIPRI, the provider of this dataset, puts on arms transfers. It doesn't measure the financial value of the arms transferred but rather the military capability they provide.

This is important because different kinds of arms are developed over time, while others might change in price based on external factors.

But the deadliness of a gun doesn't typically change. The TIV helps us compare which countries are contributing or benefitting the most from arms transfers, and how a country's transfers have change over time.

To learn more about how these numbers are calculated, [**read SIPRI's factsheet**](https://www.sipri.org/sites/default/files/files/FS/SIPRIFS1212.pdf).

## Credits

The data underpinning this map comes from the [Stockholm International Peace Research Institute](https://www.sipri.org), which licensed data from its [Arms Industry Database](https://www.sipri.org/databases/armsindustry) under Creative Commons 4.0 International.

The visualisation is by James Goldie, 360info.
::::

:::::
::::::
:::::::
