project:
  output-dir: out
  type: website
  pre-render: test.ts

website:
  twitter-card:
    creator: "@360info_global"
    image: https://360info-armstrade.pages.dev/importexportmap/arms-interactive-featuremedia.png
  open-graph:
    image: https://360info-armstrade.pages.dev/importexportmap/arms-interactive-featuremedia.png
    site-name: 360info
